name: ResidenceForm
version: '${project.version}'
main: ltd.rymc.form.residence.ResidenceForm
api-version: 1.13
depend: [ floodgate, Residence ]
authors: [ RENaa_FD ]
description: 领地Form菜单支持
website: https://rymc.ren/
